### ISSUE TITLE
debugEnable

### ISSUE THREAD

**Issue by linkyul** [Tangpj/Android-advanced-blueprint#1]
Error:(1, 0) Cannot get property 'isRunAlone' on null object
D:\project\Android-advanced-blueprint\SimpleCalces\app\build.gradle"

将project的appconfig中的debugEnable改为true报错

**Comment by Tangpj** [comment]
这是Calces中的一个bug导致的，判断lib名字的时候的bug。
你pull下代码或者对modules中的lib增加name属性就可以了
